### ISSUE TITLE
ABI Technik is not working

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1771] opened 2015-11-23 08:25 UTC
The new dependent style for ABI Technik is not working in Word nor from Zotero:

![abi-technik-error](https://cloud.githubusercontent.com/assets/5199995/11332161/7d8ab038-91c3-11e5-9c23-ab769af39ffb.jpg)

It helps to add `class="note"` in the `style` node. However, I still see then

![abi-technik-error2](https://cloud.githubusercontent.com/assets/5199995/11332216/0e3f7654-91c4-11e5-8ccc-1f7589c7dafc.jpg)

Any help?

**Comment by rmzelle** [comment] 2015-11-23 13:15
(My guess is that the "https" in the parent link somehow is giving problems)

**Comment by zuphilip** [comment] 2015-11-23 13:24
You are right! Now, it works, I will create a PR accordingly.

**Comment by zuphilip** [comment] 2015-11-23 13:32
Maybe, that is something for the validator and/or the csl-bot (especially the file-ending should be easy to check automatically).

**Comment by rmzelle** [comment] 2015-11-23 14:22
@dstillman, would this be a bug in Zotero? (in short, it looks like the "https" in `<link href="https://www.zotero.org/styles/chicago-fullnote-bibliography" rel="independent-parent"/>` trips up Zotero, as shown above)

@zuphilip, can you confirm that you get a proper HTTPS connection if you visit https://www.zotero.org/styles/chicago-fullnote-bibliography?source=1 ?

**Comment by zuphilip** [comment] 2015-11-23 14:33
![https-connection](https://cloud.githubusercontent.com/assets/5199995/11338997/84856b06-91f7-11e5-9e49-ecf12af0871c.jpg)

**Comment by rmzelle** [comment] 2015-11-23 15:30
Pinging @aurimasv as well.

**Comment by rmzelle** [comment] 2015-11-25 18:25
I can reproduce this, by the way, with Zotero Standalone 4.0.28.7. Changing the independent-parent link to use HTTPS gives the error:

```
[JavaScript Error: "Error: Style references https://www.zotero.org/styles/springer-basic-author-date, but this style is not installed" {file: "file:///C:/Users/.../zotero/styles/3-biotech.csl" line: 0}]
```

**Comment by dstillman** [comment] 2015-11-26 10:13
I'll look into this.

**Comment by rmzelle** [comment] 2015-11-27 22:47
I'm working on a fix for this.

@dstillman, with the current "master" branch I can't install local styles via the style preferences window (OS X 10.11.1, Zotero for Firefox). Instead I get a silent failure, and:

```
zotero(3): HTTP GET file:///Users/.../styles/administrative-science-quarterly.csl

zotero(3): HTTP GET file:///Users/.../styles/administrative-science-quarterly.csl succeeded with 200

Possibly unhandled rejection:

TypeError: Zotero.HTTP.promise(...).when is not a function
    Zotero.Styles</this.install<@chrome://zotero/content/xpcom/style.js:252:21
From previous event:
    Zotero_Preferences.Cite.addStyle@chrome://zotero/content/preferences/preferences_cite.js:105:4
    onclick@chrome://zotero/content/preferences/preferences.xul:1:1

TypeError: Zotero.HTTP.promise(...).when is not a function
    Zotero.Styles</this.install<@chrome://zotero/content/xpcom/style.js:252:21
From previous event:
    Zotero_Preferences.Cite.addStyle@chrome://zotero/content/preferences/preferences_cite.js:105:4
    onclick@chrome://zotero/content/preferences/preferences.xul:1:1
```

I got the same error with a checkout of master from July, so it's not a new problem. (should I report this as a GitHub issue?)

**Closed** 2015-11-30 03:41 UTC
