### ISSUE TITLE
Replace "styles-distribution" repo with "1.0.1" branch

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#4474] opened 2019-12-23 15:32 UTC
I was just contemplating whether it wouldn't be much clearer to get rid of https://github.com/citation-style-language/styles-distribution, and just have Travis CI automatically push any successful commit build in "master" to a "1.0.1" branch in this repo.

Benefits:

- Two fewer repositories (https://github.com/citation-style-language/styles-distribution and https://github.com/citation-style-language/distribution-updater can be retired).
- The "1.0.1" branch would be a stable location from where downstream projects can source v1.0.1 CSL styles, making it more straightforward for us to migrate "master" to a new CSL version whenever we want. Basically each CSL release would immediately get its own dedicated branch ("1.0", "1.0.1", etc.) from which downstream projects can source their styles. It would receive updates while the release is current and go dormant whenever we release a new CSL version.
- Probably would make it easier to address some packaging requests like https://github.com/citation-style-language/styles/pull/2706 as well.

Main question I think is whether we can easily reproduce some of the logic currently embedded in https://github.com/citation-style-language/distribution-updater/blob/master/scripts/styles_distribution.py in a Travis CI-run script (modified README.md, updating `<updated/>` timestamps with UTC commit time, deleting non ".csl" files except for renamed-styles.json).

See e.g. https://stackoverflow.com/a/52960498 and https://stackoverflow.com/a/48339945 for implementation options.

**Comment by koppor** [comment] 2020-02-27 16:45
If I get your description right, isn't that script just following:

```BASIC
10 git checkout master
20 git checkout -b 1.0.1-distribution
30 remove obsolete files from directory
40 git commit && git push
50 ... updates to master coming in ...
60 git merge master
70 git push
80 goto 50
```

For pushing, there is a GitHub action: https://github.com/ad-m/github-push-action

For executing scripts on the command line, one can use:

```yaml
    steps:
      - run: |
        git checkout 1.0.1-distribution
        git merge master
        git commit
```

The checkout has to be complete though: (see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches)

```yaml
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
```

**Comment by koppor** [comment] 2020-02-27 16:48
BTW: I suffixed `-distribution` as branch name. It is very strange that version numbers appearing like SemVer are "floating". Although I agree that this is some special thing here.

It is also not common to have branch names similar to tags. Therefore that prefix to "irritate" also on the name.

In case you prepare the branch agree that it's "just" merging, I can provide the GitHub workflow.

**Comment by koppor** [comment] 2020-02-27 16:51
[ADR](https://adr.github.io/) on the tooling

- Option `git merge`: Does not rely on external tooling and enables the change of the "REAMDE.md" using typical repository operations. Drawback: In case the "upstream" README.md changes, one has to resolve conflicts manually (or just enforces `git checkout --ours README.md` in case of a commit)
- Option [copybara](https://github.com/google/copybara): It is the leading tool to synchronize repositories. Could be complex to configure
- Option self-made scripts (as done here): Seems to be too much overhead not required at the other two options.

**Comment by rmzelle** [comment] 2020-02-27 18:08
@koppor, thanks for the input! (we're rather understaffed here and I'm not a professional programmer, so our progress on infrastructure upgrades can be slow)

We're definitely flexible on the branch naming scheme.

Regarding changes between "master" and the "*-distribution" branch, there is a bunch of stuff to consider.

* We've gotten requests to add package manager support to our styles/locales repos (like a "composer.json" for PHP's Composer (https://github.com/citation-style-language/locales/pull/161, https://github.com/citation-style-language/styles/pull/2706). I think we could just add these to the "*-distribution" branches.
* The current system (https://github.com/citation-style-language/distribution-updater/blob/master/scripts/styles_distribution.py), which runs on Zotero's servers, updates the time stamp of each CSL style to the most recent commit date of the file (this is more accurate than the manually tracked timestamps we use), replaces the README, and deletes all files except the CSL style files. I'd like to keep all that, but it would be great if we wouldn't be dependent on Zotero's servers anymore.

**Comment by rmzelle** [comment] 2020-02-27 20:21
>     * The current system ... updates the time stamp of each CSL style to the most recent commit date of the file

I assume this rules out git merge, as we would get a large amount of merge conflicts.

**Comment by koppor** [comment] 2020-02-27 20:26
Git won't store timestamps. So, after a commit, the time stamps are lost.

> NO, Git simply does not store such (meta-)information, unless you use third party tools like metastore or git-cache-meta. The only timestamp that get stored is the time patch/change was created (author time), and the time commit was created (committer time). 

https://stackoverflow.com/a/2179825/873282

Illustration:

![grafik](https://user-images.githubusercontent.com/1366654/75483759-c6539b80-59a7-11ea-9946-fb515cc0634e.png)

![grafik](https://user-images.githubusercontent.com/1366654/75483795-d3708a80-59a7-11ea-9fb8-bd08f6cdf082.png)

**Comment by rmzelle** [comment] 2020-02-27 20:35
> Git won't store timestamps.

The current code is able to pull out the git commit timestamp: https://github.com/citation-style-language/distribution-updater/blob/ca93959073c409c391e90d556d85546b823bfbf0/scripts/styles_distribution.py#L56

**Comment by koppor** [comment] 2020-02-27 21:12
Yes, you get the time stamp from the commit:

Quoting the second sentence:

> The only timestamp that get stored is the time patch/change was created (author time), and the time commit was created (committer time).

Thus, with a git merge, this information is not lost and any tooling using the git repository can reconstruct the time stamp as you did.

What I want to say: With the approach with the second repo (as currently done), the information is lost *at commit*. When you switch to branches, the information will be kept. *git magic*

Reason: git does not store time stamps *of files* unless external tools are used. The only time stamp stored is the *commit* date (and the *author date* which may differ from the cmomit date).

We can discuss hacks for separate repositories such as committing each file one by one with different author dates. 🎉

**Comment by rmzelle** [comment] 2020-02-28 17:18
Maybe I was unclear. The current script updates an XML element within each style with the timestamp of the most recent commit affecting that style. After that's done, we don't care about the timestamp metadata of the style file itself (its modification date, git commit date, or whatever).

**Comment by rmzelle** [comment] 2020-02-28 17:23
E.g. compare https://github.com/citation-style-language/styles/commit/31bacc1b4d3d8eef036340773a504ec80c971deb (no change to internal timestamp) to https://github.com/citation-style-language/styles-distribution/commit/658b4bf6cd6e71fe421b0aa401c602114b04c3dd (change to internal timestamp on line 16 based on git commit timestamp of that style in the "styles" repo).

**Comment by retorquere** [comment] 2020-11-16 15:43
> Maybe I was unclear. The current script updates an XML element within each style with the timestamp of the most recent commit affecting that style. After that's done, we don't care about the timestamp metadata of the style file itself (its modification date, git commit date, or whatever).

That's done by [this](https://github.com/citation-style-language/distribution-updater/blob/master/scripts/styles_distribution.py#L106), right? If you can walk me through what that does, functionally, I'm sure I can reproduce something likewise in the GH action workflow.

**Comment by rmzelle** [comment] 2020-11-17 02:51
> That's done by [this](https://github.com/citation-style-language/distribution-updater/blob/master/scripts/styles_distribution.py#L106), right? If you can walk me through what that does, functionally, I'm sure I can reproduce something likewise in the GH action workflow.

I think "distribution-updater" does the following:

* For every successful Travis CI build in "master" (https://github.com/citation-style-language/styles/tree/master), CSL styles are edited to replace their `<updated/>` value with the git commit time (we have no other automated systems to keep `<updated/>` updated). The CSL styles are then committed to https://github.com/citation-style-language/styles-distribution/tree/master, with a custom README and none of the other non-CSL files (like the files we use to run the test suite).

  Compare e.g. https://github.com/citation-style-language/styles/blob/3a6a4bc5e97dea24f74e7a39421437604d4e1dbe/acta-chiropterologica.csl#L17 
with https://github.com/citation-style-language/styles-distribution/blob/e9f32a1a720d5a68a77a19370469d762bea0539c/acta-chiropterologica.csl#L17.

The advantages of this are:

* Consumers of CSL styles can draw their styles from https://github.com/citation-style-language/styles-distribution/ without worrying about a potentially broken state (that said, we can also just be more disciplined and only make changes through pull requests, and maybe use a protected "master" branch with required status checks per https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-required-status-checks)
* It provides a cleaner set of styles with less cruft

Per the ticket, while the current setup works fine, it's rather complex with a dependency on Zotero's servers (running the code in https://github.com/citation-style-language/distribution-updater), and the existence of the second repo can be a bit confusing to users. I think it would be clearer if instead of pushing styles to a secondary repo, we would just push the styles to a versioned branch ("1.0.1" for the current CSL 1.0.1 styles we maintain in "master"). In addition, we've had some requests to provide a composer.json file for downstream PHP users (see https://github.com/citation-style-language/styles/pull/2706 and https://getcomposer.org/doc/01-basic-usage.md#composer-json-project-setup), which we might want to host in the cleaned-up repo/branch as well.

**Comment by retorquere** [comment] 2020-11-17 06:10
I'm not familiar with composer, and I'm not keen to touch PHP code, but updating the `updated` field and pushing to a branch is simple in GH actions. There might be a packages action for it, if not, it's a few more run lines in the current work flow file.

**Comment by retorquere** [comment] 2020-11-17 11:03
BTW git doesn't do partial commits, so I can't push the merge through to an `1.0.1` branch with only changed styles/locales but not other changes that are in the same commit (although I'd argue you should not want mixed commits anyway). I'll have to copy over the changed files, and commit that. If that's OK, that's easy. But there really isn't a difference in effort between committing them to a branch vs a different repo. It's literally the same action, I just clone the same repo and check out a branch, or clone a different repo.

**Comment by rmzelle** [comment] 2020-11-17 13:08
> I'll have to copy over the changed files, and commit that. If that's OK, that's easy. But there really isn't a difference in effort between committing them to a branch vs a different repo. It's literally the same action

Yes, that's how the current set up works, and that's fine.

> But there really isn't a difference in effort between committing them to a branch vs a different repo. It's literally the same action, I just clone the same repo and check out a branch, or clone a different repo.

If you could set up the action to commit the files to a "v1.0.1" branch in this very repo, that would allow us to easily deprecate https://github.com/citation-style-language/styles-distribution/.

**Comment by retorquere** [comment] 2020-11-17 14:10
I'm going to first test it out on my clone, then prepare a clean pull request against this repo. Just to be sure -- this workflow would run on any push to master, since I cannot distinguish between merge commits or other commits, but it will only do work when it detects that a `.csl` file has changed.

Is something similar needed for locales?

**Comment by retorquere** [comment] 2020-11-17 14:12
Also, that would be the branch `v1.0.1`, not `release/1.0.1`?

**Comment by rmzelle** [comment] 2020-11-17 14:56
I would just use `v1.0.1`. I was envisioning the following structure:

`master` > active style maintenance of 1.0.1 styles
`v1.0.1` > vetted/cleaned 1.0.1 styles populated from `master`
`v1.0` > dormant 1.0 styles (we can rename this from `1.0`)

Once 1.0.2 is out the GitHub action can be updated so the situation becomes:

`master` > active style maintenance of 1.0.2 styles
`v1.0.2` > vetted/cleaned 1.0.2 styles populated from `master`
`v1.0.1` > dormant 1.0.1 styles
`v1.0` > dormant 1.0 styles

**Comment by rmzelle** [comment] 2020-11-17 15:11
> Just to be sure -- this workflow would run on any push to master, since I cannot distinguish between merge commits or other commits, but it will only do work when it detects that a `.csl` file has changed.

Sounds good.

> Is something similar needed for locales?

Ideally yes.

**Comment by bwiernik** [comment] 2020-11-17 16:39
This sounds great.

**Comment by retorquere** [comment] 2020-11-17 17:17
Where would the locales be pushed to? Same situation, but their own repo?

**Comment by retorquere** [comment] 2020-11-17 17:22
Since the setup of these branches is not the same as master, the workflow is not going to create the branch, but will assume it to exist.

**Comment by retorquere** [comment] 2020-11-17 17:27
Alright, I'll be testing this more this evening, but I think [this](https://github.com/retorquere/styles/blob/master/.github/workflows/merge.yaml) is going to do it.

**Comment by retorquere** [comment] 2020-11-17 17:29
I have to say, GH actions are absolutely fantastic to work with. Well documented, *very* capable.

**Comment by retorquere** [comment] 2020-11-17 17:30
(oh and the merge workflow will work unchanged for both the locales and the styles repo)

**Comment by rmzelle** [comment] 2020-11-17 17:53
> Where would the locales be pushed to? Same situation, but their own repo?

Let's keep them in their own repo.

**Comment by retorquere** [comment] 2020-11-17 18:58
No I understand, but the work flow is the same? Update the timestamp and push to v1.0.1?

**Comment by rmzelle** [comment] 2020-11-17 19:03
> No I understand, but the work flow is the same? Update the timestamp and push to v1.0.1?

Yes, please. (and CSL locales have an ".xml" extension instead of an ".csl" one)

**Comment by retorquere** [comment] 2020-11-17 19:45
It'll work for both. Sheldon has been updated to only act on csl/xml depending on the repo it's ran from.

**Comment by bwiernik** [comment] 2021-12-30 18:35
I think we can close this now? @adam3smith @retorquere

**Closed by bwiernik** 2021-12-30 18:35 UTC
Labels: help wanted
