### ISSUE TITLE
APA 6th edition - In-text citation error

### ISSUE THREAD

**Issue by dsifford** [citation-style-language/styles#2531] opened 2017-02-25 18:07 UTC
Hello,

It's been reported to me [here](https://github.com/dsifford/academic-bloggers-toolkit/issues/300) that APA 6th is not parsing the in-text citations [according to the APA specification](https://owl.english.purdue.edu/owl/resource/560/03/).

Specifically, citations are listing the full range of authors twice before switching to the shortened `et al.` version.

I've confirmed this to be happening independently as well (see image below).

![image](https://cloud.githubusercontent.com/assets/5240018/23333532/fa3df340-fb5a-11e6-8ff2-830a5d39cdd8.png)

CC: @fbennett

**Comment by rmzelle** [comment] 2017-02-25 20:20
We can leave the issue here, but this isn't a problem with the style (https://github.com/Juris-M/citeproc-js would have been a better place to report this). It's most probably an issue with either the specific version of citeproc-js you're using, or in how you're feeding the item metadata to citeproc-js. We haven't seen any reports about this for other products that use citeproc-js.

https://github.com/citation-style-language/styles/blob/14d59d83f8a32f8e96d64ba5f151a07916d8ca58/apa.csl#L620 specifies `<citation et-al-min="6" et-al-use-first="1" et-al-subsequent-min="3" et-al-subsequent-use-first="1"`, which means that all subsequent cites to the same item should result in more aggressive et-al abbreviation.

**Comment by dsifford** [comment] 2017-02-25 20:39
@rmzelle Good to know! I was wondering which link of the chain was creating this issue.

The version in question for this issue is `1.1.145`. I haven't been able to try it out with the latest version.

**Comment by adam3smith** [comment] 2017-05-31 04:15
Since I can't reproduce this with recent versions of citeproc-js, I'm closing the ticket here.

**Closed by adam3smith** 2017-05-31 04:15 UTC
