### ISSUE TITLE
Fixes for Journal of Egyptian Archaeology

### ISSUE THREAD

**Issue by jfrmasters** [citation-style-language/styles#5969] opened 2022-03-17 08:33 UTC
Thanks for earlier fix on page numbers.  Other issues that I've since noticed...

First ref is like this:
M. I. Smith, ‘A Tapestry in the tomb of Horus’, in Janice Kamrin, Miroslav Barta, Salima Ikram, Mark Lehner, Mohamed Megahed (ed.), Guardian of Ancient Egypt, II (Prague, 2020), 659–71, at 662.

But (1) the editors should have initials, not their full names
And (2) Single editor is ed. but multiple should be eds without the '.'.

2nd is:
Khaled, in Janice Kamrin, Miroslav Barta, Salima Ikram, Mark Lehner, Mohamed Megahed (ed.), Guardian of Ancient Egypt, 663.

But (3) subsequent authors/editors show surname only
And (4) subsequent multiple authors/editors should list first only followed by 'et al.'

So I *think* latter should be:

Khaled, in Kamrin et al. (eds), Guardian of Ancient Egypt, 663.

Thanks for time spent on this.

**Comment by POBrien333** [comment] 2022-03-18 08:58
Hi,

Since you were already digging into the guidelines, always easier to cite the specific parts you found, as it's easier for us to then just confirm those rather than search for them ourselves. ;)


1) chapter, editor names:
Can't reproduce and renders correctly:
I. Mares, ‘Firms and the welfare state: When, why, and how does social policy matter to employers?’, **in P. A. Hall and D. Soskice (eds.)**, _Varieties of capitalism. The institutional foundations of comparative advantage_ (New York, 2001), 184–213, at 244–52.

2) editor labels, singular, plural:
fixed to "ed." and "eds"

3) chapter subsequent:
it already ONLY shoes the surname:
Mares, in Hall et al. (eds), _Varieties of capitalism. The institutional foundations of comparative advantage_, 184–213.

4) chapter subsequent editors:
editors set to 2/1

**Comment by POBrien333** [comment] 2022-03-21 14:53
@jfrmasters 
The PR just got merged. Let us know if you had any more comments/amendments.

**Comment by jfrmasters** [comment] 2022-03-22 18:45
I have fixed 3 problems but the conference paper double title still exists.  I have emailed you my updated file.  Hope this helps.

**Comment by bwiernik** [comment] 2022-04-19 08:17
@POBrien333 what’s the status of this?

**Comment by POBrien333** [comment] 2022-04-19 09:36
I've just added one edit to the PR, but I'm not willing to further work on this style due to the guidelines being a mess amongst other things.
OP seems to know CSL well enough anyway.

**Comment by bwiernik** [comment] 2022-04-19 09:43
Okay, closing for now. @jfrmasters please feel free to submit a new PR if additional changes are needed.

**Closed by bwiernik** 2022-04-19 09:43 UTC
